### ISSUE TITLE
add stack support via stack.yaml

### ISSUE THREAD

**Issue by wolftune** [nkaretnikov/titlecase#3]
I'm not sure which LTS to use, I suppose just try the latest v.3 even

**Comment by nkaretnikov** [comment]
@wolftune Hi! Sorry, for the delay. I just pushed a file which uses lts-3.6 (since that's what Snowdrift has). Let me know if it doesn't work for you. Otherwise, I'll release a new version soon (and probably on Stackage, too).

**Comment by wolftune** [comment]
all built, and all tests pass

**Comment by nkaretnikov** [comment]
@wolftune Just released a new version.
