### ISSUE TITLE
GHC 8.x cannot compile titlecase

### ISSUE THREAD

**Issue by peti** [nkaretnikov/titlecase#6]
The Cabal file prevents GHC 8.x from compiling this package due to the restriction `base >=4.7 && <4.9`. Is that intentional?

**Comment by nkaretnikov** [comment]
> The Cabal file prevents GHC 8.x from compiling this package due to the restriction base >=4.7 && <4.9. Is that intentional?
> 
> Yes, sort of. I prefer to be on the safe side, hence the bounds. Not sure whether it pays of in this particular case, though.

Do you care about this package? My spare time is focused on something else rather than Haskell at the moment. Would you like to take over?

**Comment by peti** [comment]
> Would you like to take over?

Yes, I like the titlecase tool and use it regularly. I'd be happy to take over maintenance.

**Comment by nkaretnikov** [comment]
> > Would you like to take over?
> 
> Yes, I like the titlecase tool and use it regularly. I'd be happy to take over maintenance. 

Okay, what's your Hackage account?

**Comment by nkaretnikov** [comment]
> > Would you like to take over?
> 
> Yes, I like the titlecase tool and use it regularly. I'd be happy to take over maintenance. 

Okay, what's your Hackage account?

**Comment by peti** [comment]
It's PeterSimons: http://hackage.haskell.org/user/PeterSimons

**Comment by nkaretnikov** [comment]
> It's PeterSimons: http://hackage.haskell.org/user/PeterSimons

Added you, but I don't see any changes in the web ui. Does it require confirmation by the admins?

**Comment by peti** [comment]
The link I posted earlier shows me as a maintainer for the package, so I think everything is fine. Thank you very much.

**Comment by peti** [comment]
OK, version  0.1.0.3 is out and it should fix this issue. Thank you for your help.

**Comment by nkaretnikov** [comment]
> OK, version 0.1.0.3 is out and it should fix this issue. Thank you for your help.
> 
> Thanks for volunteering. :)
